/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candle {
  'low' : bigint,
  'high' : bigint,
  'close' : bigint,
  'open' : bigint,
  'volume' : bigint,
  'timestamp' : Time,
}
export interface LiquidityBox {
  'createdAt' : Time,
  'candlesSinceCreation' : bigint,
  'isActive' : boolean,
  'maxPrice' : bigint,
  'minPrice' : bigint,
}
export interface LiquidityLine {
  'createdAt' : Time,
  'candlesSinceCreation' : bigint,
  'price' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'createLiquidityBox' : ActorMethod<[bigint, bigint], undefined>,
  'createLiquidityLine' : ActorMethod<[bigint], undefined>,
  'getAllLiquidityBoxes' : ActorMethod<[], Array<LiquidityBox>>,
  'getAllLiquidityLines' : ActorMethod<[], Array<LiquidityLine>>,
  'getMonthlyCandles' : ActorMethod<[], Array<Candle>>,
  'markBoxAsInactive' : ActorMethod<[bigint], undefined>,
  'removeLiquidityBox' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];