/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const LiquidityBox = IDL.Record({
  'createdAt' : Time,
  'candlesSinceCreation' : IDL.Nat,
  'isActive' : IDL.Bool,
  'maxPrice' : IDL.Nat,
  'minPrice' : IDL.Nat,
});
export const LiquidityLine = IDL.Record({
  'createdAt' : Time,
  'candlesSinceCreation' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Candle = IDL.Record({
  'low' : IDL.Nat,
  'high' : IDL.Nat,
  'close' : IDL.Nat,
  'open' : IDL.Nat,
  'volume' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'createLiquidityBox' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createLiquidityLine' : IDL.Func([IDL.Nat], [], []),
  'getAllLiquidityBoxes' : IDL.Func([], [IDL.Vec(LiquidityBox)], ['query']),
  'getAllLiquidityLines' : IDL.Func([], [IDL.Vec(LiquidityLine)], ['query']),
  'getMonthlyCandles' : IDL.Func([], [IDL.Vec(Candle)], ['query']),
  'markBoxAsInactive' : IDL.Func([IDL.Nat], [], []),
  'removeLiquidityBox' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const LiquidityBox = IDL.Record({
    'createdAt' : Time,
    'candlesSinceCreation' : IDL.Nat,
    'isActive' : IDL.Bool,
    'maxPrice' : IDL.Nat,
    'minPrice' : IDL.Nat,
  });
  const LiquidityLine = IDL.Record({
    'createdAt' : Time,
    'candlesSinceCreation' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Candle = IDL.Record({
    'low' : IDL.Nat,
    'high' : IDL.Nat,
    'close' : IDL.Nat,
    'open' : IDL.Nat,
    'volume' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'createLiquidityBox' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createLiquidityLine' : IDL.Func([IDL.Nat], [], []),
    'getAllLiquidityBoxes' : IDL.Func([], [IDL.Vec(LiquidityBox)], ['query']),
    'getAllLiquidityLines' : IDL.Func([], [IDL.Vec(LiquidityLine)], ['query']),
    'getMonthlyCandles' : IDL.Func([], [IDL.Vec(Candle)], ['query']),
    'markBoxAsInactive' : IDL.Func([IDL.Nat], [], []),
    'removeLiquidityBox' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };